In [10]:
#Naive bayes on Spam SMS Collection

#import the packages
#Read the csv fidsd

import pandas as pd
data=pd.read_csv('Desktop/Datasets/spam.csv',encoding='latin-1')
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [12]:
import pandas as pd
data=pd.read_csv('Desktop/Datasets/spam.csv',encoding='latin-1')

#Drop all the unwanted coloumns from the data
#Rename the coloumns with label and text

data = data.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
data = data.rename(columns={"v1":"label", "v2":"text"})
data.tail()

     label                                               text
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [13]:
import pandas as pd
data=pd.read_csv('Desktop/Datasets/spam.csv',encoding='latin-1')
data = data.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
data = data.rename(columns={"v1":"label", "v2":"text"})
data.tail()

#Map the spam emails to 1 and ham mails to 0

data['label_num'] = data.label.map({'ham':0, 'spam':1})
data.head()

  label                                               text  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [15]:
import pandas as pd
data=pd.read_csv('Desktop/Datasets/spam.csv',encoding='latin-1')
data = data.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
data = data.rename(columns={"v1":"label", "v2":"text"})
data['label_num'] = data.label.map({'ham':0, 'spam':1})

#Split the dataset for training and test sets

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data["text"],data["label"], test_size = 0.2, random_state = 10)

#Make a matrix of 1-grams in the training set
#We can change it to 2-gram, 3-gram etc accordingly

from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(ngram_range=(1, 1))

#Fit this to training set
vect.fit(X_train)


#Do the tfidf transformations in this stage

X_train_df = vect.transform(X_train)
X_test_df = vect.transform(X_test)


#Apply Multinomial Naive bayes algorithm to the dataset


from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_df,y_train)
prediction= model.predict(X_test_df)


#Calculate the accuracy


from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)

0.98834080717488793